[package]
name = "neural_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.4"
rand = "0.9.0-alpha.0"
conv = "0.3.3"
indicatif = "0.17.8"
byteorder = "1.5.0"
image = "0.25.0"
num-traits = "0.2.18"
serde = { version = "1.0.197", features = ["derive"] }
chrono = "0.4.37"
rocket = "0.5.0"

[profile.release]
lto = "fat"
